@startuml domainModel

skinparam linetype polyline
skinparam linetype ortho

class User {
    +name: String
    +email: String
    +password: String
    +validated: Boolean
}

class Place {
    +name: String
    +location: String
    +type: String
}

enum AccessibilityIssue {
}

class Report {
    +reportDate: Date
    +status: String
}

User "1" -- "*" Report
Place "1" -- "*" Report

Report "1" -- "*" AccessibilityIssue : contains >

note right of User
A user must be validated before 
they can report accessibility issues.
A user can only report each place once.
end note

note right of Place
A place can have 
multiple reports, 
but each report is 
tied to a specific user.
end note

note right of AccessibilityIssue
A report can contain
multiple predefined 
accessibility issues.
end note

@enduml
