@startuml physicalModel
title Deployment Diagram
node "Smartphone" {
    frame "<<executionEnvironment>> Android" {
        artifact "Inclui.apk\n(Flutter)"
    }
}

node "Firebase"

node "Google Maps Host" {
    component "Google Maps API"
    component "Google Maps Logic"
    database "Google Maps DB"
}

' Connections
"Inclui.apk\n(Flutter)" ..> "Firebase" : Uses
"Inclui.apk\n(Flutter)" ..> "Google Maps API" : Calls
"Google Maps API" ..> "Google Maps Logic" : Processes
"Google Maps Logic" ..> "Google Maps DB" : Stores/Retrieves

@enduml